#   A basic travis.yml for EthTransport project

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.11.13

before_install:
  - export DJANGO_SETTINGS_MODULE=guzo.travis_settings
  - export PYTHONPATH=$HOME/builds/etmdb/EthTransport
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.pip
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - python manage.py syncdb --noinput

#TODO command to run the test suite
# script:
#  - python manage.py test